CREATE TABLE campaigns (
    Campaign_ID           INT PRIMARY KEY,
    Company               VARCHAR(100),
    Campaign_Type         VARCHAR(50),
    Target_Audience       VARCHAR(50),
    Duration              VARCHAR(20),
    Duration_Days         INT,
    Channel_Used          VARCHAR(50),
    Conversion_Rate       DECIMAL(6,4),
    Conversion_Rate_Pct   DECIMAL(6,2),
    Acquisition_Cost      DECIMAL(12,2),
    ROI                   DECIMAL(6,2),
    ROI_Bucket            VARCHAR(30),
    Revenue_Generated     DECIMAL(14,2),
    Net_Profit            DECIMAL(14,2),
    Location              VARCHAR(50),
    Language              VARCHAR(30),
    Clicks                INT,
    Impressions           INT,
    CTR_Pct               DECIMAL(8,4),
    Cost_Per_Click        DECIMAL(10,4),
    Est_Conversions       INT,
    Cost_Per_Conversion   DECIMAL(10,2),
    Engagement_Score      INT,
    Customer_Segment      VARCHAR(50),
    Campaign_Date         DATE,
    Year                  INT,
    Month                 INT,
    Month_Name            VARCHAR(10),
    Quarter               INT
);